### ISSUE TITLE
Update setup documentation with mongo and redis dependencies

### ISSUE THREAD

**Issue by sudheesh001** [mozillascience/PaperBadger#158]
Update local run instructions to include mongo and redis dependencies

-------------------------------

I've tried to set up this repository locally and faced a lot of issues in the process because the `Run Locally` part of the documentation doesn't clearly specify that both a `mongod` and `redis-server` needs to be running so that this application could be set up, It'd be better to inform before the `npm start` step that these are also required to set up this application correctly or it'll throw errors as follows.

I think this information should be added so that it's easier.
```sh
> PaperBadger@0.1.1 build:js /Users/sudheeshsinganamalla/Documents/PaperBadger
> webpack --config webpack.config.js --progress --profile --colors

 10% 0/1 build modulesPaperBadger started on port:  5000
connection!
2031ms build modules
3ms seal
5ms optimize
9ms hashing
27ms create chunk assets
1ms additional chunk assets
0ms optimize chunk assets
0ms optimize assets
59ms emit
Hash: 3e63d72527870a8331a1
Version: webpack 1.12.14
Time: 2164ms
  Asset    Size  Chunks             Chunk Names
main.js  995 kB       0  [emitted]  main
    + 242 hidden modules
TypeError: Cannot set property 'redirect' of undefined
    at /Users/sudheeshsinganamalla/Documents/PaperBadger/src/app.js:168:28
    at Layer.handle [as handle_request] (/Users/sudheeshsinganamalla/Documents/PaperBadger/node_modules/express/lib/router/layer.js:82:5)
    at next (/Users/sudheeshsinganamalla/Documents/PaperBadger/node_modules/express/lib/router/route.js:100:13)
    at Route.dispatch (/Users/sudheeshsinganamalla/Documents/PaperBadger/node_modules/express/lib/router/route.js:81:3)
    at Layer.handle [as handle_request] (/Users/sudheeshsinganamalla/Documents/PaperBadger/node_modules/express/lib/router/layer.js:82:5)
    at /Users/sudheeshsinganamalla/Documents/PaperBadger/node_modules/express/lib/router/index.js:234:24
    at Function.proto.process_params (/Users/sudheeshsinganamalla/Documents/PaperBadger/node_modules/express/lib/router/index.js:312:12)
    at /Users/sudheeshsinganamalla/Documents/PaperBadger/node_modules/express/lib/router/index.js:228:12
    at Function.match_layer (/Users/sudheeshsinganamalla/Documents/PaperBadger/node_modules/express/lib/router/index.js:295:3)
    at next (/Users/sudheeshsinganamalla/Documents/PaperBadger/node_modules/express/lib/router/index.js:189:10)
    at /Users/sudheeshsinganamalla/Documents/PaperBadger/node_modules/express/lib/router/index.js:191:16
    at Function.match_layer (/Users/sudheeshsinganamalla/Documents/PaperBadger/node_modules/express/lib/router/index.js:295:3)
    at next (/Users/sudheeshsinganamalla/Documents/PaperBadger/node_modules/express/lib/router/index.js:189:10)
    at /Users/sudheeshsinganamalla/Documents/PaperBadger/node_modules/express/lib/router/index.js:191:16
    at Function.match_layer (/Users/sudheeshsinganamalla/Documents/PaperBadger/node_modules/express/lib/router/index.js:295:3)
    at next (/Users/sudheeshsinganamalla/Documents/PaperBadger/node_modules/express/lib/router/index.js:189:10)
    at /Users/sudheeshsinganamalla/Documents/PaperBadger/node_modules/express/lib/router/index.js:191:16
    at Function.match_layer (/Users/sudheeshsinganamalla/Documents/PaperBadger/node_modules/express/lib/router/index.js:295:3)
    at next (/Users/sudheeshsinganamalla/Documents/PaperBadger/node_modules/express/lib/router/index.js:189:10)
    at /Users/sudheeshsinganamalla/Documents/PaperBadger/node_modules/express/lib/router/index.js:191:16
    at Function.match_layer (/Users/sudheeshsinganamalla/Documents/PaperBadger/node_modules/express/lib/router/index.js:295:3)
    at next (/Users/sudheeshsinganamalla/Documents/PaperBadger/node_modules/express/lib/router/index.js:189:10)

```

**Comment by acabunoc** [comment]
Good point! Updated issue and added 'good first bug' label
